config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  use_doorkeeper
    post 'lti_launch/oidc_login', to: "lti_launch#oidc_login"
    get 'lti_launch/oidc_login', to: "lti_launch#oidc_login"
    post 'lti_launch/launch', to: "lti_launch#launch"
    get 'lti_launch/launch', to: "lti_launch#launch"
    post 'lti_nrps/sync_roster', to: "lti_nrps#sync_roster"
  get 'lti_config/index', to: "lti_config#index"
  post 'github_config/update_config', to: "github_config#update_config"
  post 'lti_config/update_config', to: "lti_config#update_config"
  post 'smtp_config/update_config', to: "smtp_config#update_config"
  post 'smtp_config/send_test_email', to: "smtp_config#send_test_email"
  post 'oauth_config/update_oauth', to: "oauth_config#update_oauth_config"

  namespace :oauth, { defaults: { format: :json } } do
    get "device_flow_init", to: "device_flow#init"
    get "device_flow_authorize", to: "device_flow#authorize"
  end

  namespace :api, { defaults: { format: :json } } do
    namespace :v1 do
      get "user", to: "user#show"

      resources :courses, param: :name, only: [:index, :create] do
        resources :course_user_data, only: [:index, :create, :show, :update, :destroy],
                                     param: :email, :constraints => { :email => /[^\/]+/ }

        resources :assessments, param: :name, only: [:index, :show] do
          resources :problems, only: [:index, :create]
          get "writeup"
          get "handout"
          post "submit"
          post "set_group_settings"
          resources :groups, only: [:index, :show, :create, :destroy]

          resources :submissions, param: :version, only: [:index] do
            get "feedback"
          end

          resources :scores, only: [:index, :show],
                    param: :email, :constraints => { :email => /[^\/]+/ }

          put "scores/:email/update_latest", :constraints => { :email => /[^\/]+/ }, to: "scores#update_latest"
        end
      end

      match "*path", to: "base_api#render_404", via: :all
    end
  end

  root "courses#courses_redirect"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" },
                     path_prefix: "auth"

  get "courses", to: "courses#index"

  namespace :home do
    if Rails.env == "development" || Rails.env == "test"
      match "developer_login", via: [:get, :post]
    end
    get "contact"
    get "no_user"
  end

  # device_flow-related
  get "activate", to: "device_flow_activation#index", as: :device_flow_activation
  get "device_flow_resolve", to: "device_flow_activation#resolve"
  get "device_flow_auth_cb", to: "device_flow_activation#authorization_callback"

  resources :file_manager, param: :path, path: 'file_manager', only: [:index] do
    collection do
      post 'upload', to: 'file_manager#upload'
      post '/', to: 'file_manager#upload'
      post 'download_tar', to: 'file_manager#download_tar'
      get ':path', to: 'file_manager#index', constraints: { path: /.+/ }, as: :path
      put ':path', to: 'file_manager#rename', constraints: { path: /.+/ }, as: :rename
      post ':path', to: 'file_manager#upload', constraints: { path: /.+/ }, as: :upload_path
      delete ':path', to: 'file_manager#delete', constraints: { path: /.+/ }, as: :delete
    end
  end

  resource :admin, :except => [:show] do
    match "email_instructors", via: [:get, :post]
    post "clear_cache"
    get "autolab_config"
  end

  resources :users do
    get "admin"
    get "download_all_submissions", on: :member
    get "github_oauth", on: :member
    get "lti_launch_initialize", on: :member
    post "lti_launch_link_course", on: :member
    post "github_revoke", on: :member
    get "github_oauth_callback", on: :collection
    match "update_password_for_user", on: :member, via: [:get, :put]
    post "change_password_for_user", on: :member
    patch "update_display_settings", on: :member
  end

  resources :courses, param: :name do
    match "join_course", via: [:get, :post], on: :collection

    resources :schedulers do
      post "visualRun", action: :visual_run
      post "run"
    end

    resource :metrics, only: :index do
      get "index"
      get "get_current_metrics"
      get "get_watchlist_instances"
      get "get_num_pending_instances"
      post "refresh_watchlist_instances"
      get "get_watchlist_configuration"
      post "update_current_metrics"
      post "update_watchlist_instances"
      post "update_watchlist_configuration"
    end

    resource :dockers, only: :index do
      get "index"
      post "uploadDockerImage"
    end

    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new]
      resources :submissions, except: [:show] do
        resources :annotations, only: [:create, :update, :destroy] do
          collection do
            get "shared_comments"
          end
        end

        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "view"
          post "release_student_grade"
          post "unrelease_student_grade"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        post "releaseAllGrades"
        post "releaseSectionGrades"
        get "viewFeedback"
        get "getPartialFeedback"
        post "reload"
        get "statistics"
        post "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "install_assessment"
        get "course_onboard_install_asmt"
        post "import_assessment"
        post "import_assessments"
        post "import_asmt_from_tar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        post "bulk_release"
        get "csv"
        post "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        post "unsudo"
      end
    end

    member do
      post "bulk_release"
      get "download_roster"
      post "unlink_course"
      patch "update_lti_settings"
      match "email", via: [:get, :post]
      get "export"
      post "export_selected"
      get "manage"
      get "moss"
      post "reload"
      match "report_bug", via: [:get, :post]
      post "run_moss"
      get "sudo"
      match "upload_roster", via: [:get, :post]
      post "add_users_from_emails"
      get "user_lookup"
      get "users"
    end

    collection do
      post "create_from_tar"
    end
  end

  resource :github_integration, only: [] do
    get "get_repositories"
    get "get_branches"
    get "get_commits"
  end

  get "/404", to: "home#error_404"
  get "/500", to: "home#error_500"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :assessment_user_data
  has_many :course_user_data, through: :assessment_user_data
  before_destroy :clear_members

  delegate :size, to: :assessment_user_data

  def is_member(aud)
    aud.group_id == id && aud.group_confirmed(AssessmentUserDatum::CONFIRMED)
  end

  def enough_room_for(aud, group_size)
    aud.group_id == id || size < group_size
  end

  # If the only members left in the group are those pending group confirmation,
  # then the group is as good as empty since only confirmed members can potentially add them
  def is_effectively_empty
    assessment_user_data.where(membership_status: [AssessmentUserDatum::GROUP_CONFIRMED,
                                                   AssessmentUserDatum::CONFIRMED]).empty?
  end

private

  def clear_members
    assessment_user_data.each(&:leave_group)
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < Api::V1::BaseApiController
  before_action -> { require_privilege :instructor_all }

  before_action :set_assessment

  # endpoint to obtain all groups
  def index
    show_members = params[:show_members].to_boolean
    groups = @assessment.groups(show_members: show_members)

    if show_members
      groups_json = []
      groups.each do |group|
        group_json = get_group_json(group)
        groups_json << group_json
      end
    else
      groups_json = groups.as_json
    end

    group_size = @assessment.group_size

    respond_with({ group_size: group_size,
                   groups: groups_json,
                   assessment: @assessment })
  end

  def show
    require_params([:id])
    group = @assessment.groups(show_members: true).find_by(id: params[:id])

    if group.nil?
      raise ApiError.new("Couldn't find group with id #{params[:id]}", :bad_request)
    end

    group_json = get_group_json(group)

    respond_with group_json
  end

  # create group endpoint
  def create
    require_params([:groups])

    if @assessment.group_size <= 1
      raise ApiError.new("Group size of assessment is currently 1,"\
                         " so you can't create group", :bad_request)
    end
    group_members = params[:groups].map{ |group| group["group_members"] }

    if !group_members&.select{ |list| list.length > @assessment.group_size }&.empty?
      raise ApiError.new("Cannot have groups with size more than group_size", :bad_request)
    end

    all_emails = params[:groups].map{ |group| group["group_members"] }.flatten.uniq
    all_cuds = @course.course_user_data.joins(:user).where(users: { email: all_emails })

    all_cud_ids = all_cuds.map(&:id)
    all_auds = @assessment.assessment_user_data.where(course_user_datum_id: all_cud_ids )

    email_to_cuds = all_cuds.map{ |cud| { cud.email => cud } }.reduce({}, :merge)
    cuds_to_auds =  all_auds.map{ |aud| { aud.course_user_datum_id => aud } }.reduce({}, :merge)

    params[:groups].each do |g|
      group = Group.new
      group.name = g["name"] || "Unnamed Group"
      count = 0
      g["group_members"].each do |group_member|
        aud = cuds_to_auds[email_to_cuds[group_member]&.id]
        next unless aud&.group_confirmed(AssessmentUserDatum::UNCONFIRMED)

        aud.group = group
        aud.membership_status = AssessmentUserDatum::CONFIRMED
        count += 1 if aud.save!
      end
      group.save! if count > 0
    end

    respond_with_hash(@assessment.groups)
  end

  # endpoint to delete groups
  def destroy
    require_params([:id])
    group = @assessment.groups.find_by(id: params[:id].to_i)
    if group.nil?
      raise ApiError.new("Couldn't find group #{params[:id]}", :bad_request)
    end

    ActiveRecord::Base.transaction do
      group.assessment_user_data.each do |aud|
        aud.group_id = nil
        aud.membership_status = AssessmentUserDatum::UNCONFIRMED
        aud.save!
      end
      group.destroy!
    end
    respond_with_hash(message: "Group #{params[:id]} successfully deleted")
  end

private

  def get_group_json(group)
    members = []
    group.assessment_user_data.each do |assessment_user_datum|
      user_json = assessment_user_datum.course_user_datum.user.as_json
      user_json[:course_user_datum_id] = assessment_user_datum.course_user_datum_id
      members << user_json
    end

    group_json = group.as_json
    group_json[:members] = members
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def groups_back_link
    if @cud.instructor
      link_to "Back", course_assessment_groups_path(@course, @assessment)
    else
      link_to "Back", current_assessment_path
    end
  end

  # Whether a user can make certain changes to group membership
  # - cancel outgoing membership requests
  # - confirm / deny incoming membership requests
  # - add users to group (send an outgoing membership request)
  def user_can_edit_group?
    (@group.is_member(@aud) && @assessment.allow_student_assign_group) || @cud.instructor
  end
end

app/views/groups/_form.html.erb
<%= form_for @group, url: course_assessment_group_url(@course, @assessment, @group), builder: FormBuilderWithDateTimeInput do |f| %>
  <%= f.text_field :name, help_text: "Change the name of this group." %>

  <%= f.submit "Change Name" %>
<% end %>

app/views/groups/_list_item.html.erb
<li>
  <h4><%= group.name %></h4>
  <p><b><%= group.assessment_user_data.all.map{ |aud| aud.course_user_datum.full_name }.join(", ") %></b></p>
  <p>
    <%= link_to "Ask to Join Group", join_course_assessment_group_path(@course, @assessment, group), method: :post %>
    <% if @cud.instructor %>
      | <%= link_to "View", course_assessment_group_path(@course, @assessment, group) %>
      | <%= link_to "Destroy", course_assessment_group_path(@course, @assessment, group),
                    method: :delete, data: { confirm: "Are you sure you want to disband this group?" } %>
    <% end %>
  </p>
</li>

app/views/groups/_new_form.html.erb
<%= form_tag action: :create do %>
  <div class="form-group">
    <label class="control-label" for="group_name">Group Name</label>
    <%= text_field_tag :group_name, nil, class: "form-control", autocomplete: "off" %>
    <p class="help-block">Set the name of this group.</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="member_email">Partner Email</label>
    <%= text_field_tag :member_email, nil, class: "form-control", autocomplete: "email" %>
    <% if @assessment.allow_student_assign_group %>
      <p class="help-block">The email of your desired partner. They will need to confirm their membership.</p>
    <% else %>
      <%# Instructor adding a student %>
      <p class="help-block">The email of your desired partner. Their membership will be automatically confirmed.</p>
    <% end %>
  </div>

  <%= submit_tag "Create Group", class: "btn btn-primary" %>
<% end %>

app/views/groups/index.html.erb
<% @title = "Groups" %>

<h4>Groups</h4>
<% unless @assessment.allow_student_assign_group %>
  <ul class="collection">
    <li class="collection-item">
      Students are not allowed to self-assign groups for this assessment.
      <br>
      For convenience, you will not be added to groups that you create and students do not need to confirm their membership.
    </li>
  </ul>
<% end %>
<% if @groups.size > 0 %>

  <table class=prettyBorder>
    <tr>
      <th>Group Name</th>

      <% @assessment.group_size.times do |i| %>
        <th>Member</th>
      <% end %>

      <th>Options</th>
    </tr>

    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, course_assessment_group_path(@course, @assessment, group) %></td>

        <% group.assessment_user_data.each do |aud| %>
          <% cud = aud.course_user_datum %>
          <td>
            <%= cud.email %>
            <% unless aud.group_confirmed then %>
              (Unconfirmed)
            <% end %>
          </td>
        <% end %>

        <% (@assessment.group_size - group.assessment_user_data.size).times do %>
          <td>&ndash;</td>
        <% end %>

        <td>
          <%= link_to "Edit", course_assessment_group_path(@course, @assessment, group) %> |
          <%= link_to "Destroy", course_assessment_group_path(@course, @assessment, group),
                      method: :delete, data: { confirm: "Are you sure you want to disband this group?" } %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>
    No Groups have been set yet.
  </p>
<% end %>

<br>
<%= link_to new_course_assessment_group_path(@course, @assessment) do %>
  <span class="btn primary">
    Create New Group
  </span>
<% end %>

<% if @grouplessCUDs.size > 0 %>
  <h4>Users Without Groups</h4>

  <ul class="small gray-box">
    <% @grouplessCUDs.each do |cud| %>
      <li><b><%= cud.email %></b></li>
    <% end %>
  </ul>
<% end %>

<% if @groupAssessments.size > 0 %>
  <h4>Load Groups from Another Assessment</h4>
  <%= form_tag import_course_assessment_groups_path(@course, @assessment) do %>
    <%= select_tag :ass, options_from_collection_for_select(@groupAssessments, :id, :name) %>
    <%= submit_tag 'Import Groups', class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<% @title = "Create New Group" %>

<h4>Create New Group</h4>

<% if @assessment.allow_student_assign_group || @cud.instructor %>
  <%= render "new_form" %>

  <% if @unfullGroups.size > 0 %>
    <h4>Join a Group</h4>

    <ul class="gray-box">
      <% @unfullGroups.each do |group| %>
        <%= render "list_item", { group: } %>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <p>
    Sorry, you are not allowed to create or join groups for this assessment.
    Contact your instructor for group assignment.
  </p>
<% end %>

<div style="margin-top: 1em">
  <%= groups_back_link %>
</div>

app/views/groups/show.html.erb
<% @title = "Group: #{@group.name}" %>
<h4>Group: <%= @group.name %></h4>

<% if @aud.group_id == @group.id %>
  <% if (@aud.membership_status & AssessmentUserDatum::MEMBER_CONFIRMED) == 0 %>
    <p>You have not confirmed your group membership yet.</p>
    <% if @assessment.allow_student_assign_group || @cud.instructor %>
      <%= link_to "Confirm Membership", join_course_assessment_group_path(@course, @assessment, @group), method: :post %> |
      <%= link_to "Deny Membership", leave_course_assessment_group_path(@course, @assessment, @group), method: :post %>
    <% else %>
      <p>Contact your instructor to confirm your group membership.</p>
    <% end %>
  <% elsif (@aud.membership_status & AssessmentUserDatum::GROUP_CONFIRMED) == 0 %>
    <p>Your group has not confirmed your membership yet.</p>
  <% end %>
<% end %>

<% if @aud.group_confirmed || @cud.instructor %>
  <%= render "form" %>
<% end %>

<h4>Group Members</h4>
<ul class="gray-box">
  <% @group.assessment_user_data.each do |aud| %>
    <li>
      <% cud = aud.course_user_datum %>
      <strong><%= "#{cud.full_name} (#{cud.email})" %></strong>
      <% if !aud.group_confirmed(AssessmentUserDatum::MEMBER_CONFIRMED) %>
        <p>This member has not confirmed their membership yet.</p>
        <% if user_can_edit_group? %>
          <p>
            <%= link_to "Cancel Request",
                        leave_course_assessment_group_path(@course, @assessment, @group, member_id: cud.id),
                        method: :post %>
          </p>
        <% end %>
      <% elsif !aud.group_confirmed(AssessmentUserDatum::GROUP_CONFIRMED) %>
        <p>This member has not been confirmed by the group yet.</p>
        <% if user_can_edit_group? %>
          <p>
            <%= link_to "Confirm Membership",
                        add_course_assessment_group_path(@course, @assessment, @group, member_id: cud.id),
                        method: :post %> |
            <%= link_to "Deny Membership",
                        leave_course_assessment_group_path(@course, @assessment, @group, member_id: cud.id),
                        method: :post %>
          </p>
        <% end %>
      <% elsif @cud.instructor %>
        <p>
          <%= link_to "Kick Member",
                      leave_course_assessment_group_path(@course, @assessment, @group, member_id: cud.id),
                      method: :post %>
        </p>
      <% end %>
    </li>
  <% end %>
</ul>

<% if user_can_edit_group? %>
  <% if @group.assessment_user_data.size < @assessment.group_size %>
    <h4>Invite Another Student to Join This Group</h4>
    <%= form_tag add_course_assessment_group_path(@course, @assessment, @group) do %>
      <div class="form-group">
        <label class="control-label" for="member_email">Partner Email</label>
        <%= text_field_tag :member_email, nil, class: "form-control", autocomplete: "email" %>
        <% if @assessment.allow_student_assign_group %>
          <p class="help-block">The email of your desired partner. They will need to confirm their membership.</p>
        <% else %>
          <%# Instructor adding a student %>
          <p class="help-block">The email of your desired partner. Their membership will be automatically confirmed.</p>
        <% end %>
      </div>

      <%= submit_tag "Invite to Group", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <p>No more members can be added as the group is already at the maximum size.</p>
  <% end %>
<% elsif @group.is_member(@aud) && !@assessment.allow_student_assign_group %>
  <p>
    You are not allowed to add members to your group for this assessment.
    Contact your instructor for group assignment.
  </p>
<% end %>
<%# else: student assignment is allowed, but user is not a member of the group yet. We don't have to display anything %>

<div style="margin-top: 1em">
  <% if @aud.group_id == @group.id && (@assessment.allow_student_assign_group || @cud.instructor) %>
    <%= link_to "Leave Group", leave_course_assessment_group_path(@course, @assessment, @group),
                { method: :post, data: { confirm: "Are you sure you want to leave your group?" } } %> |
  <% end %>
  <%= groups_back_link %>
</div>