config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  use_doorkeeper
    post 'lti_launch/oidc_login', to: "lti_launch#oidc_login"
    get 'lti_launch/oidc_login', to: "lti_launch#oidc_login"
    post 'lti_launch/launch', to: "lti_launch#launch"
    get 'lti_launch/launch', to: "lti_launch#launch"
    post 'lti_nrps/sync_roster', to: "lti_nrps#sync_roster"
  get 'lti_config/index', to: "lti_config#index"
  post 'github_config/update_config', to: "github_config#update_config"
  post 'lti_config/update_config', to: "lti_config#update_config"
  post 'smtp_config/update_config', to: "smtp_config#update_config"
  post 'smtp_config/send_test_email', to: "smtp_config#send_test_email"
  post 'oauth_config/update_oauth', to: "oauth_config#update_oauth_config"

  namespace :oauth, { defaults: { format: :json } } do
    get "device_flow_init", to: "device_flow#init"
    get "device_flow_authorize", to: "device_flow#authorize"
  end

  namespace :api, { defaults: { format: :json } } do
    namespace :v1 do
      get "user", to: "user#show"

      resources :courses, param: :name, only: [:index, :create] do
        resources :course_user_data, only: [:index, :create, :show, :update, :destroy],
                                     param: :email, :constraints => { :email => /[^\/]+/ }

        resources :assessments, param: :name, only: [:index, :show] do
          resources :problems, only: [:index, :create]
          get "writeup"
          get "handout"
          post "submit"
          post "set_group_settings"
          resources :groups, only: [:index, :show, :create, :destroy]

          resources :submissions, param: :version, only: [:index] do
            get "feedback"
          end

          resources :scores, only: [:index, :show],
                    param: :email, :constraints => { :email => /[^\/]+/ }

          put "scores/:email/update_latest", :constraints => { :email => /[^\/]+/ }, to: "scores#update_latest"
        end
      end

      match "*path", to: "base_api#render_404", via: :all
    end
  end

  root "courses#courses_redirect"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "registrations" },
                     path_prefix: "auth"

  get "courses", to: "courses#index"

  namespace :home do
    if Rails.env == "development" || Rails.env == "test"
      match "developer_login", via: [:get, :post]
    end
    get "contact"
    get "no_user"
  end

  # device_flow-related
  get "activate", to: "device_flow_activation#index", as: :device_flow_activation
  get "device_flow_resolve", to: "device_flow_activation#resolve"
  get "device_flow_auth_cb", to: "device_flow_activation#authorization_callback"

  resources :file_manager, param: :path, path: 'file_manager', only: [:index] do
    collection do
      post 'upload', to: 'file_manager#upload'
      post '/', to: 'file_manager#upload'
      post 'download_tar', to: 'file_manager#download_tar'
      get ':path', to: 'file_manager#index', constraints: { path: /.+/ }, as: :path
      put ':path', to: 'file_manager#rename', constraints: { path: /.+/ }, as: :rename
      post ':path', to: 'file_manager#upload', constraints: { path: /.+/ }, as: :upload_path
      delete ':path', to: 'file_manager#delete', constraints: { path: /.+/ }, as: :delete
    end
  end

  resource :admin, :except => [:show] do
    match "email_instructors", via: [:get, :post]
    post "clear_cache"
    get "autolab_config"
  end

  resources :users do
    get "admin"
    get "download_all_submissions", on: :member
    get "github_oauth", on: :member
    get "lti_launch_initialize", on: :member
    post "lti_launch_link_course", on: :member
    post "github_revoke", on: :member
    get "github_oauth_callback", on: :collection
    match "update_password_for_user", on: :member, via: [:get, :put]
    post "change_password_for_user", on: :member
    patch "update_display_settings", on: :member
  end

  resources :courses, param: :name do
    match "join_course", via: [:get, :post], on: :collection

    resources :schedulers do
      post "visualRun", action: :visual_run
      post "run"
    end

    resource :metrics, only: :index do
      get "index"
      get "get_current_metrics"
      get "get_watchlist_instances"
      get "get_num_pending_instances"
      post "refresh_watchlist_instances"
      get "get_watchlist_configuration"
      post "update_current_metrics"
      post "update_watchlist_instances"
      post "update_watchlist_configuration"
    end

    resource :dockers, only: :index do
      get "index"
      post "uploadDockerImage"
    end

    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new]
      resources :submissions, except: [:show] do
        resources :annotations, only: [:create, :update, :destroy] do
          collection do
            get "shared_comments"
          end
        end

        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "view"
          post "release_student_grade"
          post "unrelease_student_grade"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        post "releaseAllGrades"
        post "releaseSectionGrades"
        get "viewFeedback"
        get "getPartialFeedback"
        post "reload"
        get "statistics"
        post "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "install_assessment"
        get "course_onboard_install_asmt"
        post "import_assessment"
        post "import_assessments"
        post "import_asmt_from_tar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        post "bulk_release"
        get "csv"
        post "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        post "unsudo"
      end
    end

    member do
      post "bulk_release"
      get "download_roster"
      post "unlink_course"
      patch "update_lti_settings"
      match "email", via: [:get, :post]
      get "export"
      post "export_selected"
      get "manage"
      get "moss"
      post "reload"
      match "report_bug", via: [:get, :post]
      post "run_moss"
      get "sudo"
      match "upload_roster", via: [:get, :post]
      post "add_users_from_emails"
      get "user_lookup"
      get "users"
    end

    collection do
      post "create_from_tar"
    end
  end

  resource :github_integration, only: [] do
    get "get_repositories"
    get "get_branches"
    get "get_commits"
  end

  get "/404", to: "home#error_404"
  get "/500", to: "home#error_500"
end

app/controllers/home_controller.rb
##
# The Home Controller houses (ha) any action that's available to the general public.
#
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :set_course
  skip_before_action :authorize_user_for_course
  skip_before_action :authenticate_for_action
  skip_before_action :update_persistent_announcements

  def developer_login
    return unless request.post?

    user = User.find_by(email: params[:email])
    if user
      sign_in :user, user
      flash[:success] = "Signed in as #{user.display_name}"
      redirect_to(root_path)
    else
      flash[:error] = "User with Email: '#{params[:email]}' doesn't exist"
      redirect_to home_developer_login_path
    end
  end

  def contact
    # --- empty ---
    # This route just renders the home#contact page, nothing special
  end

  def error_404; end

  def error_500; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<h1>Contact Autolab</h1>

<p class="lead">
Hey there! We're committed to doing the absolute best job we can to make your
experience on Autolab amazing. Here are some frequently asked questions:
</p>

<div class="row">
  <div class="col l6">
    <h3>I have an issue with the way my assignment was graded.</h3>
    <p>
    That's not exactly a question, but you should probably check with your
    professor. They're the ones who can help with regrades, getting grading
    feedback, questions about due dates, and other class-specific details.
    </p>
  </div>
  <div class="col l6">
    <h3>Can you add me to [this class I'm supposed to be in]?</h3>
    <p>
    No, sorry. Once again, you'll have to check with your professor for this one.
    </p>
  </div>
</div><!-- container -->
<hr>
<div class="row">
  <div class="col l6">
    <h3>I'm seeing a picture of Donkey Kong... what just happened?</h3>
    <p>
    Something with Autolab just broke&mdash;it definitely wasn't supposed to
    happen. Read the next two questions to figure out where to go from here!
    </p>
  </div>
  <div class="col l6">
    <h3>What should I do if I've encountered an error or if I'd like to request a feature?</h3>
    <p>
    Jump on over to our <b><a href="https://github.com/autolab/Autolab/issues/">issue tracker
    on GitHub</a></b>. From there, you can search for already-reported issues (to make
    sure the one you have in mind hasn't already been reported) and then create an
    issue detailing what's wrong or what you'd like to see happen. Make sure to read
    below for what makes a good error report.
    </p>
  </div>
  <div class="col l6">
    <h3>I don't have a GitHub account or I'd like a little bit more personalized bug resolution experience. Is there an alternative to the issue tracker?</h3>
    <p>
    In this case, feel free to send an email to the Autolab developers mailing list,
    </p>
    <p>
    <b><%= Rails.configuration.school['support_email'] %></b>
    </p>
    <p>
    We get a good deal of traffic on this list, but we'll make our best effort to
    get back to as soon as we can. Make sure to read below for what makes a good
    error report.
    </p>
  </div>
  <div class="col l6">
    <h3>What makes a good error report?</h3>
    <p>
    When reporting an issue or requesting a feature, please be as descriptive as possible! Good issue reports have
    <ul>
      <li>screenshots</li>
      <li>stack traces (if you saw an error page and it gave you one)</li>
      <li>a description of what you think you did to generate the error</li>
      <li>a description of what you think should have happened</li>
    </ul>
    </p>
  </div>
</div><!-- container -->
<hr>
<div class="row">
  <div class="col l6">
    <h3>Where can I learn more about Autolab?</h3>
    <p>
    For more information about the Autolab Project and team, check out our <b><a href="http://www.autolabproject.com/">
      project page</a></b>. For more information about how to get started using Autolab for your own autograding
      adventures, check out the <b><a href="https://github.com/autolab/Autolab/">GitHub repository</a></b>.
      The README and the Wiki have good documentation about how to get up and running.
      If you encounter an issue along the way, report it or send us an email!
    </p>
  </div>
  <div class="col l6">
    <h3>Can I help with Autolab development?</h3>
    <p>
    Yes! Autolab is completely open source, from the frontend Rails app to the backend autograding and VM management
      system called <b><a href="https://github.com/autolab/Tango">Tango</a></b>, and we welcome any external
      contributions. If you're interested in contributing to Autolab,
      check out the <b><a href="https://github.com/autolab/Autolab/">GitHub repository</a></b>!
    </p>
  </div>
</div><!-- container -->

app/views/home/developer_login.html.erb
<% @title = "Developer Login" %>

<h4>Development Autolab</h4>
<p>
  Enter the email of the user you wish to sign in as.
</p>

<%= form_tag do %>
  <div class="input-field">
    <%= email_field_tag :email, nil, autocomplete: "email" %>
    <label for="email">Email</label>
  </div>
  <%= submit_tag 'Sign In', { class: "btn primary" } %>
<% end %>

app/views/home/error_404.html.erb
<h2>404 &ndash; Not found</h2>

<h2 style="margin-bottom:0px"><%= @errorMessage %></h2>

<% if flash[:error] %><p><b><%= flash[:error] %></b></p><% end %>

<p><b>Oops!</b> Find this page Autolab can not. If you believe there should be something here please email us at  <a href="mailto:<%= Rails.configuration.school['support_email'] %>"><%= Rails.configuration.school['support_email'] %></a>, with the page that you were trying to access.</p>

<%= image_tag "DonkeyKong.jpg", width: '200px' %>

<% if @error then %>
  <br><br>
  <p><i>Remember that if you modify any config files, you'll need to  reload them for the changes to take effect.</i><br>
    <% if @course_name then %>
      <b><%= link_to "Reload Course Config",
                     reload_course_path(name: @course_name) %></b><br>
      <% if @assessment_name then %>
        <b><%= link_to "Reload Assessment Config",
                       reload_course_assessment_path(course_name: @course_name,
                                                     name: @assessment_name) %></b>
      <% end %>
    <% end %>
  </p>

  <p>
    <h3>Error Information</h3>
    <pre><%= debug(@error) %></pre>
  </p>
  <p>
    <h3>Stack Dump</h3>
    <pre><%= processStackDump(@error.backtrace).join("<br>").html_safe %></pre>
  </p>
<% end %>

<div>
  <a href="/"><%= Rails.configuration.school['school_short_name'] %> Autolab</a>
  <p>Questions or problems? Please <a href="/home/contact">contact us</a>.</p>
</div>

app/views/home/error_500.html.erb
<h2>500 &ndash; Internal error</h2>

<h2 style="margin-bottom:0px"><%= @errorMessage %></h2>

<% if flash[:error] %><p><b><%= flash[:error] %></b></p><% end %>

<p><b>Oops!</b> Autolab seems to have done something wrong. We have been notified about this and will look into it. If you would like to file a Bug Report, you may email us at <a href="mailto:<%= Rails.configuration.school['support_email'] %>"><%= Rails.configuration.school['support_email'] %></a> or open an issue in our <a href="https://github.com/autolab/Autolab/issues/">issue tracker</a> on GitHub.</p>

<%= image_tag "DonkeyKong.jpg", width: '200px' %>

<% if @error then %>
  <br><br>
  <p><i>Remember that if you modify any config files, you'll need to reload them for the changes to take effect.</i><br>
    <% if @course_name then %>
      <b><%= link_to "Reload Course Config",
                     reload_course_path(name: @course_name), data: { method: "post" } %></b><br>
      <% if @assessment_name then %>
        <b><%= link_to "Reload Assessment Config",
                       reload_course_assessment_path(course_name: @course_name,
                                                     name: @assessment_name), data: { method: "post" } %></b>
      <% end %>
    <% end %>
  </p>

  <p>
    <h3>Error Information</h3>
    <pre><%= debug(@error) %></pre>
  </p>
  <p>
    <h3>Stack Dump</h3>
    <pre><%= processStackDump(@error.backtrace).join("<br>").html_safe %></pre>
  </p>
<% end %>

<div>
  <a href="/"><%= Rails.configuration.school['school_short_name'] %> Autolab</a>
  <p>Questions or problems? Please <a href="/home/contact">contact us</a>.</p>
</div>

app/views/home/no_user.html.erb
<h1>Welcome to Autolab!</h1>

<p class="lead">
Hey there! We noticed that you're not currently associated with any courses.
Here are some resources to get you started.
</p>

<h2>For students</h2>

<div class="container">
  <div class="row">
    <div class="col l6">
      <h3>How can I join a course?</h3>
      <p>
      If your instructor has provided you with an access code, you can join the course via the button below.

      Otherwise, fire off an email to your instructor and they can make sure that you get added.
      </p>
      <%= link_to "<i class='material-icons left'>add</i> Join Course".html_safe, join_course_courses_path, title: "Join Course", class: "btn btn-large red darken-3" %>
    </div>
  </div><!-- row -->
</div><!-- container -->

<h2>For instructors</h2>

<div class="container">
  <div class="row">
    <div class="col l6">
      <h3>How can I create my course?</h3>
      <p>
      You should ask your system administrator to create your course for you. If
      you're also the system administrator, see the section below!
      </p>
    </div>

    <div class="col l6">
      <h3>How do I manage my course?</h3>
      <p>
      We've got a bunch of documentation for how to create documentation online
      at <a href="https://docs.autolabproject.com/">https://docs.autolabproject.com/</a>.
      Specifically, you'll want to check out the
      <a href="https://docs.autolabproject.com/instructors/">Instructor
      Guide</a>.
      </p>
    </div>
  </div><!-- row -->

  <div class="row">
    <div class="col l6">
      <h3>How do I write an assessment autograder?</h3>
      <p>
      The instructions for creating labs, autograders, and assessments are also
      online at
      <a href="https://docs.autolabproject.com/">https://docs.autolabproject.com/</a>,
      in the section called
      <a href="https://docs.autolabproject.com/lab/">Lab Author Guide</a>.
      </p>
    </div>
  </div><!-- row -->
</div><!-- container -->

<h2>For administrators</h2>

<div class="container">
  <div class="row">
    <div class="col l6">
      <h3>I just set up Autolab. How can I make myself an admin?</h3>
      <p>
      We have a Rake task that you can run where your app is deployed to promote
      any user to the admin level. Just run <code>rake
      'admin:promote_user[you@example.com]'</code> to give a user administrative
      privileges. Note that the user has to exist already.
      </p>
    </div>

    <div class="col l6">
      <h3>Where can I keep up to date on releases and updates?</h3>
      <p>
      You can see information about each official release of Autolab
      <a href="https://github.com/autolab/Autolab/releases">on GitHub</a>.
      </p>
    </div>
  </div><!-- row -->

  <div class="row">
    <div class="col l6">
      <h3>Where is the Autolab documentation?</h3>
      <p>
      We've migrated our documentation to the Github Docs
      <ul>
        <li><a href="https://docs.autolabproject.com/">Autolab Docs</a></li>
      </ul>
      </p>
    </div>

    <div class="col l6">
      <h3>Can I get in contact with the Autolab developers?</h3>
      <p>
      Yes, we love hearing from our users!
      <ul>
        <li>
        If you have feature suggestions or are experiencing a minor bug, use our
        <a href="https://github.com/autolab/Autolab/issues/">issue tracker</a>.
        </li>
        <li>
        If you need help troubleshooting something related to Autolab that
        doesn't belong on our issue tracker, you can email us at <b><%= Rails.configuration.school['tech_email'] %></b>.
        </li>
      </ul>
      </p>
    </div>
  </div><!-- row -->
</div><!-- container -->

<%= begin
      render partial: "topannounce"
    rescue StandardError
      nil
    end %>